### ISSUE TITLE
替换AK和SK后，运行应用出错

### ISSUE THREAD

**Issue by NancyZY** [buhe/present-demo#1]
操作步骤如下：
1） 安装 npm i react-native-qiniu --save
2） 安装之后替换demo的AK和SK
3） 运行
提示错误“undefined is not an object”(evaluating 'qiniu.conf.ACCESS_KEY = 'XXXXXXX';'),此处的‘XXXXXXX’为七牛个人中心的AK

（PS: 运行原库的demo没有问题，所以，应该跟运行环境无关，如果需要，可以贴出来配置）

**Comment by buhe** [comment]
谢谢反馈，这里文档需要更新一下

**Comment by buhe** [comment]
参考一下 github.com/qiniu/react-native-sdk ,用了 es6 style 之后 API 发生了改动
